name: BitzAPI
main: com.rayzr522.bitzapi.BitzAPI
version: 1.1
description: A random API with a bunch of random utilities thrown together into one jar
author: Rayzr522
depend: [Vault]
commands:
  bitz:
    description: Main BitzAPI command
    aliases: bz